name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - type: pre-exclude
    when:
      label: 'skip-changelog'

  - type: version-resolver
    semver-increment: major
    when:
      label: 'major'
  - type: version-resolver
    semver-increment: minor
    when:
      label: 'minor'
  - type: version-resolver
    semver-increment: patch
    when:
      label: 'patch'
  - type: version-resolver
    semver-increment: patch

  - title: '⚠️ Breaking Changes'
    semver-increment: minor
    when:
      label: 'breaking'
  - title: '🚀 Features'
    semver-increment: minor
    when:
      label: 'feature'
  - title: '💪 Enhancement'
    semver-increment: minor
    when:
      label: 'enhancement'
  - title: '🐛 Bug Fixes'
    when:
      label: 'bug'
  - title: '🧰 Maintenance'
    when:
      label: 'chore'
  - title: '🔧 Refactoring'
    when:
      label: 'refactor'
  - title: '📖 Documentation'
    when:
      label: 'documentation'
  - title: '⛓️ Dependency update'
    when:
      label: 'dependencies'
  - title: '🧩 Other Changes'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

sort-by: merged_at
sort-direction: descending

template: |
  ## Changes

  $CHANGES

autolabeler:
  - label: breaking
    branch:
      - '/^release[/]v0[.][0-9]+([/-].*)?$/'
    title:
      - '/^[a-z]+(?:\([^)]+\))?!:/i'
    body:
      - '/BREAKING[ -]CHANGE:/i'
  - label: feature
    branch:
      - '/^feat(ure)?[/-].+/'
    title:
      - '/^feat(?:\([^)]+\))?!?:/i'
  - label: bug
    branch:
      - '/^fix[/-].+/'
    title:
      - '/^fix(?:\([^)]+\))?!?:/i'
  - label: chore
    branch:
      - '/^chore[/-].+/'
      - '/^ci[/-].+/'
    title:
      - '/^(?:build|chore|ci|perf|test)(?:\([^)]+\))?!?:/i'
  - label: refactor
    branch:
      - '/^(?:refactor|refactoring)[/-].+/'
    title:
      - '/^refactor(?:\([^)]+\))?!?:/i'
  - label: documentation
    branch:
      - '/^docs?(?:umentation)?[/-].+/'
    title:
      - '/^docs?(?:\([^)]+\))?!?:/i'
    files:
      - 'README.md'
      - 'docs/**'
      - 'website/content/**'
      - 'website/docs/**'
  - label: enhancement
    branch:
      - '/^(?:enhancement|improve)[/-].+/'
    title:
      - '/^(?:enhance|improve|optimize|refine)(?:\([^)]+\))?!?:/i'
  - label: dependencies
    branch:
      - '/^(?:dependabot|renovate)[/-].+/'
    title:
      - '/^(?:build|chore)\(deps\)!?:/i'
