pub mod analyze;
#[cfg(feature = "hw")]
pub mod auto;
#[cfg(feature = "hw")]
pub mod automeasure;
#[cfg(feature = "hw")]
pub mod autoshot;
pub mod completions;
pub mod config;
#[cfg(feature = "hw")]
pub mod fetch;
pub mod kerr;
pub mod li;
pub mod monitor;
pub mod phase;
#[cfg(feature = "hw")]
pub mod process;
pub mod raw;
pub mod reference;
#[cfg(feature = "hw")]
pub mod screenshot;
pub mod sensor;
pub mod show;
#[cfg(feature = "hw")]
pub mod single;
#[cfg(feature = "hw")]
pub mod trigger;
