use serde::Serialize;

use super::LATEST_CONFIG_VERSION;
use crate::docs::DOCS_FORMAT_VERSION;

#[derive(Debug, Clone, Copy, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RequiredState {
    Required,
    Optional,
    Conditional,
}

#[derive(Debug, Clone, Copy, Serialize, PartialEq, Eq)]
pub struct ConfigFieldDoc {
    pub id: &'static str,
    pub path: &'static str,
    pub value_type: &'static str,
    pub required: RequiredState,
    pub default: Option<&'static str>,
    pub valid_values: &'static [&'static str],
    pub units: Option<&'static str>,
    pub since: u32,
    pub summary_en: &'static str,
    pub details_en: &'static str,
    pub summary_ja: &'static str,
    pub details_ja: &'static str,
    pub constraints: &'static [&'static str],
}

#[derive(Debug, Serialize, PartialEq, Eq)]
pub struct ConfigReference {
    pub format_version: u32,
    pub pmoke_version: &'static str,
    pub schema_version: u32,
    pub fields: &'static [ConfigFieldDoc],
}

#[allow(clippy::too_many_arguments)]
const fn field(
    path: &'static str,
    value_type: &'static str,
    required: RequiredState,
    default: Option<&'static str>,
    valid_values: &'static [&'static str],
    units: Option<&'static str>,
    summary_en: &'static str,
    details_en: &'static str,
    summary_ja: &'static str,
    details_ja: &'static str,
    constraints: &'static [&'static str],
) -> ConfigFieldDoc {
    ConfigFieldDoc {
        id: path,
        path,
        value_type,
        required,
        default,
        valid_values,
        units,
        since: 4,
        summary_en,
        details_en,
        summary_ja,
        details_ja,
        constraints,
    }
}

use RequiredState::{Conditional, Optional, Required};

pub const CONFIG_FIELD_DOCS: &[ConfigFieldDoc] = &[
    field(
        "version",
        "integer",
        Required,
        None,
        &["5"],
        None,
        "Configuration schema version.",
        "New and migrated configurations use schema version 5.",
        "設定スキーマのバージョン",
        "新規設定と移行済み設定で使用するバージョン5。",
        &["must equal 5"],
    ),
    field(
        "scope",
        "table",
        Required,
        None,
        &[],
        None,
        "Oscilloscope configuration.",
        "Selects one registered scope model and its transport URI.",
        "オシロスコープ設定",
        "登録済みモデルと通信URIの組み合わせ。",
        &[],
    ),
    field(
        "scope.model",
        "string",
        Required,
        None,
        &["DHO5108"],
        None,
        "Oscilloscope driver model.",
        "The model must match an oscilloscope registered by the instruments crate.",
        "オシロスコープモデル",
        "instruments crateに登録されたモデル名との一致。",
        &["must be a registered oscilloscope model"],
    ),
    field(
        "scope.connection",
        "connection URI",
        Required,
        None,
        &["tcp://", "visa:", "gpib://"],
        None,
        "Oscilloscope transport URI.",
        "DHO5108 normally uses direct TCP/IP and never uses a Prologix transport.",
        "オシロスコープの通信URI",
        "DHO5108で使用するdirect TCP/IP。Prologix transport対象外。",
        &["transport must be supported by the model and build features"],
    ),
    field(
        "generator",
        "table",
        Optional,
        Some("absent"),
        &[],
        None,
        "Optional function-generator configuration.",
        "Required only by commands that trigger or automate a measurement.",
        "任意のファンクションジェネレータ設定",
        "triggerまたは自動測定系commandで必要な装置設定。",
        &["required by trigger, autoshot, automeasure, and auto"],
    ),
    field(
        "generator.model",
        "string",
        Conditional,
        None,
        &["WF1946B"],
        None,
        "Function-generator driver model.",
        "Required when the generator table is present.",
        "ファンクションジェネレータモデル",
        "generator table使用時に必要な登録名。",
        &["must be a registered generator model"],
    ),
    field(
        "generator.connection",
        "connection URI",
        Conditional,
        None,
        &["gpib://", "prologix-tcp://", "prologix-serial://"],
        None,
        "Function-generator transport URI.",
        "The URI selects native GPIB or a Prologix TCP/serial controller.",
        "ファンクションジェネレータの通信URI",
        "native GPIBまたはPrologix TCP/serialの選択。",
        &["transport must be supported by the model and build features"],
    ),
    field(
        "data",
        "table",
        Required,
        None,
        &[],
        None,
        "Acquisition storage and analysis-input policy.",
        "Controls canonical waveform formats and optional screenshot capture.",
        "取得データ方針",
        "標準波形形式と任意のスクリーンショット取得の設定。",
        &[],
    ),
    field(
        "data.output",
        "string enum",
        Required,
        None,
        &["csv", "raw", "both"],
        None,
        "Waveform format written by acquisition.",
        "Raw is preferred for very large captures; both also writes CSV.",
        "取得波形の保存形式",
        "大規模取得向けraw、CSV併記向けboth。",
        &[],
    ),
    field(
        "data.input",
        "string enum",
        Required,
        None,
        &["csv", "raw", "auto"],
        None,
        "Waveform source used by analysis.",
        "Auto selects available canonical data, preferring verified raw data.",
        "解析波形の入力形式",
        "利用可能な標準データを選ぶauto。検証済みraw優先。",
        &[],
    ),
    field(
        "data.screenshot",
        "boolean",
        Optional,
        Some("false"),
        &["true", "false"],
        None,
        "Oscilloscope screenshot capture.",
        "Capture requires a scope and transport that support display transfer.",
        "オシロスコープ画面取得",
        "display transfer対応モデル・通信方式での任意取得。",
        &["DHO5108 capture requires TCP/IP or USB-TMC"],
    ),
    field(
        "sensors",
        "array of tables",
        Conditional,
        Some("[]"),
        &[],
        None,
        "Sensor-channel metadata and scaling.",
        "Each entry assigns one channel and exactly one scaling strategy.",
        "センサーチャンネル一覧",
        "各channelと単一scale方針の対応。",
        &["channels must not overlap reference or lock-in signal channels"],
    ),
    field(
        "sensors[].channel",
        "integer",
        Required,
        None,
        &[],
        None,
        "Oscilloscope sensor channel.",
        "The current DHO5108 mapping accepts channels 1 through 8.",
        "センサーチャンネル番号",
        "DHO5108向け1以上8以下の番号。",
        &["1 <= value <= 8", "must be unique across all channel roles"],
    ),
    field(
        "sensors[].scale",
        "inline table union",
        Required,
        None,
        &["{ factor = ... }", "{ max_abs = ..., polarity = ... }"],
        None,
        "Sensor conversion rule.",
        "Choose direct multiplication or maximum-absolute normalization.",
        "センサー変換規則",
        "直接係数または最大絶対値正規化の択一。",
        &["factor and max_abs forms are mutually exclusive"],
    ),
    field(
        "sensors[].scale.factor",
        "float",
        Conditional,
        None,
        &[],
        None,
        "Linear sensor conversion factor.",
        "Multiplies the integrated sensor values directly.",
        "線形センサー変換係数",
        "積分センサー値への直接乗算。",
        &["must be finite and non-zero"],
    ),
    field(
        "sensors[].scale.max_abs",
        "float",
        Conditional,
        None,
        &[],
        None,
        "Target maximum absolute sensor value.",
        "Normalizes the measured absolute maximum to this positive target.",
        "最大絶対値の正規化目標",
        "測定最大絶対値に対応する正の目標値。",
        &["must be finite and positive"],
    ),
    field(
        "sensors[].scale.polarity",
        "integer enum",
        Conditional,
        None,
        &["-1", "1"],
        None,
        "Polarity for maximum-absolute scaling.",
        "Required with max_abs scaling.",
        "最大絶対値正規化の極性",
        "max_abs使用時の必須符号。",
        &["must equal -1 or 1"],
    ),
    field(
        "sensors[].label",
        "string",
        Required,
        None,
        &[],
        None,
        "Plot label for the sensor.",
        "Matplotlib mathtext may be supplied as a TOML literal string.",
        "センサープロットラベル",
        "TOML literal stringで指定可能なMatplotlib mathtext。",
        &["must not be empty"],
    ),
    field(
        "sensors[].unit",
        "string",
        Required,
        None,
        &[],
        None,
        "Output unit for the scaled sensor.",
        "Used in tables, plots, and saved analysis headers.",
        "変換後センサーの出力単位",
        "表・プロット・解析保存headerでの単位。",
        &["must not be empty"],
    ),
    field(
        "pulse",
        "table",
        Required,
        None,
        &[],
        None,
        "Pulse background windows.",
        "Defines baseline regions before and after the pulse.",
        "パルス背景区間",
        "パルス前後のベースライン領域。",
        &["background windows must not overlap"],
    ),
    field(
        "pulse.background_before",
        "inline time window",
        Required,
        None,
        &[],
        Some("s"),
        "Background window before the pulse.",
        "An inline table with finite start and end values.",
        "パルス前背景区間",
        "有限なstartとendのinline table。",
        &["start < end"],
    ),
    field(
        "pulse.background_after",
        "inline time window",
        Required,
        None,
        &[],
        Some("s"),
        "Background window after the pulse.",
        "An inline table with finite start and end values.",
        "パルス後背景区間",
        "有限なstartとendのinline table。",
        &["start < end"],
    ),
    field(
        "reference",
        "table",
        Required,
        None,
        &[],
        None,
        "Optical reference analysis settings.",
        "Controls the reference channel, FFT region, and fit decimation.",
        "光学参照信号の解析設定",
        "reference channel、FFT区間、fit間引きの指定。",
        &[],
    ),
    field(
        "reference.channel",
        "integer",
        Required,
        None,
        &[],
        None,
        "Reference oscilloscope channel.",
        "The current DHO5108 mapping accepts channels 1 through 8.",
        "参照信号チャンネル",
        "DHO5108向け1以上8以下の番号。",
        &["1 <= value <= 8", "must be unique across all channel roles"],
    ),
    field(
        "reference.fft_window",
        "inline time window",
        Required,
        None,
        &[],
        Some("s"),
        "Time range used by the reference FFT.",
        "Choose a stable reference segment with finite start and end values.",
        "参照FFTの時間区間",
        "安定した参照信号区間を表す有限なstartとend。",
        &["start < end"],
    ),
    field(
        "reference.stride_samples",
        "integer",
        Required,
        None,
        &[],
        Some("samples"),
        "Reference-fit decimation stride.",
        "Larger values reduce fitting cost at the expense of temporal detail.",
        "参照fitの間引き幅",
        "計算量と時間分解能の調整値。",
        &["must be positive"],
    ),
    field(
        "reference.window_samples",
        "integer",
        Required,
        None,
        &[],
        Some("samples"),
        "Local reference-fitting window size.",
        "Used around the FFT estimate by reference analysis.",
        "局所参照fitの窓幅",
        "FFT推定値周辺で使用するsample数。",
        &["must be positive"],
    ),
    field(
        "lockin",
        "table",
        Required,
        None,
        &[],
        None,
        "Numerical lock-in settings.",
        "Defines signal channels, parallelism, output stride, and low-pass filtering.",
        "数値lock-in設定",
        "信号channel、並列度、出力間引き、low-pass filterの指定。",
        &[],
    ),
    field(
        "lockin.signal_channels",
        "integer array",
        Conditional,
        None,
        &[],
        None,
        "Channels demodulated by lock-in analysis.",
        "At least one channel is required by lock-in and downstream analysis.",
        "lock-in 復調対象チャンネル",
        "lock-inと後段解析で必要な1件以上のchannel番号。",
        &[
            "each value must be in 1..=8",
            "must be unique across all channel roles",
        ],
    ),
    field(
        "lockin.workers",
        "integer",
        Required,
        None,
        &[],
        None,
        "Parallel lock-in worker count.",
        "Values near the physical CPU count are a practical starting point.",
        "lock-inの並列worker数",
        "物理CPU数付近を初期値とする並列度。",
        &["must be positive"],
    ),
    field(
        "lockin.stride_samples",
        "integer",
        Required,
        None,
        &[],
        Some("samples"),
        "Lock-in output stride in input samples.",
        "Input sample rate divided by this value gives the output sample rate.",
        "lock-in 出力間引き幅",
        "入力sample rateを割るsample数。出力sample rateを決定。",
        &["must be positive"],
    ),
    field(
        "lockin.filter",
        "tagged inline table",
        Required,
        None,
        &[],
        None,
        "Lock-in low-pass filter configuration.",
        "The current runtime accepts the boxcar_legacy kind; fields from other kinds are not part of schema v5.",
        "lock-in low-pass filter 設定",
        "schema v5ではboxcar_legacyのみを使用。",
        &["fields from other filter kinds are rejected"],
    ),
    field(
        "lockin.filter.kind",
        "string enum",
        Required,
        None,
        &["boxcar_legacy"],
        None,
        "Lock-in filter algorithm.",
        "boxcar_legacy is the only active LPF. Historical FIR and IIR kinds are readable only for migration diagnostics.",
        "lock-in filter アルゴリズム",
        "現在のLPFはboxcar_legacyのみ。過去のFIR/IIR kindは移行診断のためだけに読み取る。",
        &[],
    ),
    field(
        "lockin.filter.half_window_cycles",
        "float",
        Required,
        None,
        &[],
        Some("reference cycles"),
        "Half-window scale in reference cycles.",
        "The boxcar integration window extends symmetrically by this many reference cycles.",
        "参照周期単位の半窓幅",
        "boxcar積分窓を参照周期単位で指定する半窓幅。",
        &["must be finite and positive"],
    ),
    field(
        "lockin.debug_output",
        "boolean",
        Optional,
        Some("false"),
        &["true", "false"],
        None,
        "Lock-in debug artifact output.",
        "Enable only for filter inspection because artifacts can be large.",
        "lock-in debug artifact 出力",
        "filter調査時のみ有効化する大容量artifact出力。",
        &[],
    ),
    field(
        "lockin.debug_label",
        "string",
        Optional,
        Some("absent"),
        &[],
        None,
        "Safe suffix for debug artifacts.",
        "The label is restricted to a short ASCII filename-safe subset.",
        "debug artifactの安全なsuffix",
        "短いASCII filename-safe文字列。",
        &[
            "1-64 ASCII alphanumeric, '.', '_', or '-'",
            "must not be '.' or '..'",
        ],
    ),
    field(
        "lockin.debug_overwrite",
        "boolean",
        Optional,
        Some("false"),
        &["true", "false"],
        None,
        "Debug artifact overwrite policy.",
        "Allows replacement of an existing matching debug output.",
        "debug artifact 上書き方針",
        "同名debug出力の置換許可。",
        &[],
    ),
    field(
        "lockin.snr_background_window",
        "inline time window",
        Optional,
        Some("absent"),
        &[],
        Some("s"),
        "Optional background window for SNR diagnostics.",
        "An inline table with finite start and end values.",
        "SNR 診断用背景区間",
        "有限なstartとendの任意inline table。",
        &["start < end"],
    ),
    field(
        "lockin.snr_signal_window",
        "inline time window",
        Optional,
        Some("absent"),
        &[],
        Some("s"),
        "Optional signal window for SNR diagnostics.",
        "An inline table with finite start and end values.",
        "SNR 診断用信号区間",
        "有限なstartとendの任意inline table。",
        &["start < end"],
    ),
    field(
        "lockin.save_npy",
        "boolean",
        Optional,
        Some("false"),
        &["true", "false"],
        None,
        "NumPy output for lock-in results.",
        "Writes NPY artifacts in addition to canonical CSV results.",
        "lock-in結果のNumPy出力",
        "標準CSVに追加するNPY artifact。",
        &[],
    ),
    field(
        "phase",
        "table",
        Required,
        None,
        &[],
        None,
        "Phase-rotation settings.",
        "Contains offsets for the first six harmonic components.",
        "位相回転設定",
        "第1から第6高調波のoffset。",
        &[],
    ),
    field(
        "phase.offsets",
        "float or expression array",
        Required,
        None,
        &[],
        Some("rad"),
        "Six harmonic phase offsets.",
        "Numeric expressions such as pi/2 are accepted.",
        "6高調波の位相offset",
        "pi/2などの数式指定に対応するrad値。",
        &["must contain exactly 6 finite values"],
    ),
    field(
        "kerr",
        "table",
        Required,
        None,
        &[],
        None,
        "Kerr-angle conversion settings.",
        "Selects calibration sensor, calculation method, and final factor.",
        "Kerr角変換設定",
        "校正sensor、計算法、最終係数の指定。",
        &[],
    ),
    field(
        "kerr.sensor",
        "integer",
        Required,
        None,
        &[],
        None,
        "Sensor channel used for Kerr calibration.",
        "The channel must also exist in the sensors array.",
        "Kerr 校正用センサーチャンネル",
        "sensors配列に存在するchannel。",
        &["must reference sensors[].channel"],
    ),
    field(
        "kerr.method",
        "string enum",
        Required,
        None,
        &["standard", "harmonics"],
        None,
        "Kerr calculation method.",
        "Selects the standard or harmonic analysis implementation.",
        "Kerr 計算法",
        "standardまたはharmonics実装の選択。",
        &[],
    ),
    field(
        "kerr.factor",
        "float",
        Required,
        None,
        &[],
        None,
        "Final Kerr conversion factor.",
        "Applied after the selected Kerr calculation.",
        "最終Kerr変換係数",
        "選択したKerr計算後の乗算値。",
        &["must be finite"],
    ),
    field(
        "plot",
        "table",
        Optional,
        Some("defaults"),
        &[],
        None,
        "Plot generation settings.",
        "Controls display/save behavior, decimation, and error policy.",
        "プロット生成設定",
        "表示・保存、間引き、失敗方針の指定。",
        &[],
    ),
    field(
        "plot.mode",
        "string enum",
        Optional,
        Some("save"),
        &["off", "save", "interactive", "both"],
        None,
        "Plot output mode.",
        "Batch use normally selects save; interactive opens Matplotlib windows.",
        "plot出力mode",
        "batch向けsaveとMatplotlib window向けinteractive。",
        &[],
    ),
    field(
        "plot.max_points",
        "integer",
        Optional,
        Some("100000"),
        &[],
        Some("points per series"),
        "Maximum points passed to plotting.",
        "Lower values improve Matplotlib responsiveness on large captures.",
        "プロット入力の最大点数",
        "大規模取得時のMatplotlib応答性調整値。",
        &["must be positive"],
    ),
    field(
        "plot.decimation",
        "string enum",
        Optional,
        Some("stride"),
        &["none", "stride", "min_max"],
        None,
        "Plot downsampling algorithm.",
        "min_max preserves narrow extrema better than stride decimation.",
        "プロット間引きアルゴリズム",
        "狭い極値の保持に適したmin_max。",
        &[],
    ),
    field(
        "plot.on_error",
        "string enum",
        Optional,
        Some("warn"),
        &["warn", "fail"],
        None,
        "Plot failure policy.",
        "Warn preserves successful analysis; fail makes plotting errors fatal.",
        "プロット失敗方針",
        "解析成功を保持するwarnと致命扱いのfail。",
        &[],
    ),
    field(
        "plot.output_dir",
        "string",
        Optional,
        Some("absent"),
        &[],
        None,
        "Deprecated plot directory compatibility field.",
        "Version 5 accepts but ignores this field; artifacts use the canonical run layout.",
        "非推奨のplot directory互換field",
        "version 5で受理後に無視される値。artifactは標準run layout。",
        &["ignored with a warning"],
    ),
];

pub fn config_reference() -> ConfigReference {
    ConfigReference {
        format_version: DOCS_FORMAT_VERSION,
        pmoke_version: env!("CARGO_PKG_VERSION"),
        schema_version: LATEST_CONFIG_VERSION,
        fields: CONFIG_FIELD_DOCS,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;

    #[test]
    fn field_ids_are_unique_and_stable_paths() {
        let mut ids = BTreeSet::new();
        for field in CONFIG_FIELD_DOCS {
            assert_eq!(field.id, field.path);
            assert!(ids.insert(field.id), "duplicate config field: {}", field.id);
            assert!(!field.summary_en.is_empty());
            assert!(!field.summary_ja.is_empty());
        }
    }

    #[test]
    fn reference_uses_current_versions() {
        let reference = config_reference();
        assert_eq!(reference.pmoke_version, env!("CARGO_PKG_VERSION"));
        assert_eq!(reference.schema_version, LATEST_CONFIG_VERSION);
    }
}
