use serde::Serialize;

use super::LATEST_CONFIG_VERSION;
use crate::docs::DOCS_FORMAT_VERSION;

#[derive(Debug, Clone, Copy, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RequiredState {
    Required,
    Optional,
    Conditional,
}

#[derive(Debug, Clone, Copy, Serialize, PartialEq, Eq)]
pub struct ConfigFieldDoc {
    pub id: &'static str,
    pub path: &'static str,
    pub value_type: &'static str,
    pub required: RequiredState,
    pub default: Option<&'static str>,
    pub valid_values: &'static [&'static str],
    pub units: Option<&'static str>,
    pub since: u32,
    pub summary_en: &'static str,
    pub details_en: &'static str,
    pub summary_ja: &'static str,
    pub details_ja: &'static str,
    pub constraints: &'static [&'static str],
}

#[derive(Debug, Serialize, PartialEq, Eq)]
pub struct ConfigReference {
    pub format_version: u32,
    pub pmoke_version: &'static str,
    pub schema_version: u32,
    pub fields: &'static [ConfigFieldDoc],
}

#[allow(clippy::too_many_arguments)]
const fn field(
    path: &'static str,
    value_type: &'static str,
    required: RequiredState,
    default: Option<&'static str>,
    valid_values: &'static [&'static str],
    units: Option<&'static str>,
    summary_en: &'static str,
    details_en: &'static str,
    summary_ja: &'static str,
    details_ja: &'static str,
    constraints: &'static [&'static str],
) -> ConfigFieldDoc {
    ConfigFieldDoc {
        id: path,
        path,
        value_type,
        required,
        default,
        valid_values,
        units,
        since: 4,
        summary_en,
        details_en,
        summary_ja,
        details_ja,
        constraints,
    }
}

use RequiredState::{Conditional, Optional, Required};

pub const CONFIG_FIELD_DOCS: &[ConfigFieldDoc] = &[
    field(
        "version",
        "integer",
        Required,
        None,
        &["4"],
        None,
        "Configuration schema version.",
        "New and migrated configurations use schema version 4.",
        "設定スキーマ版",
        "新規設定と移行済み設定で使用するバージョン 4。",
        &["must equal 4"],
    ),
    field(
        "scope",
        "table",
        Required,
        None,
        &[],
        None,
        "Oscilloscope configuration.",
        "Selects one registered scope model and its transport URI.",
        "オシロスコープ設定",
        "登録済みモデルと通信 URI の組み合わせ。",
        &[],
    ),
    field(
        "scope.model",
        "string",
        Required,
        None,
        &["DHO5108"],
        None,
        "Oscilloscope driver model.",
        "The model must match an oscilloscope registered by the instruments crate.",
        "オシロスコープモデル",
        "instruments crate の登録名との一致。",
        &["must be a registered oscilloscope model"],
    ),
    field(
        "scope.connection",
        "connection URI",
        Required,
        None,
        &["tcp://", "visa:", "gpib://"],
        None,
        "Oscilloscope transport URI.",
        "DHO5108 normally uses direct TCP/IP and never uses a Prologix transport.",
        "オシロスコープ通信 URI",
        "DHO5108 で通常使用する直接 TCP/IP。Prologix 対象外。",
        &["transport must be supported by the model and build features"],
    ),
    field(
        "generator",
        "table",
        Optional,
        Some("absent"),
        &[],
        None,
        "Optional function-generator configuration.",
        "Required only by commands that trigger or automate a measurement.",
        "任意のファンクションジェネレータ設定",
        "trigger または自動測定系コマンドで必要な装置設定。",
        &["required by trigger, autoshot, automeasure, and auto"],
    ),
    field(
        "generator.model",
        "string",
        Conditional,
        None,
        &["WF1946B"],
        None,
        "Function-generator driver model.",
        "Required when the generator table is present.",
        "ファンクションジェネレータモデル",
        "generator table 使用時の必須登録名。",
        &["must be a registered generator model"],
    ),
    field(
        "generator.connection",
        "connection URI",
        Conditional,
        None,
        &["gpib://", "prologix-tcp://", "prologix-serial://"],
        None,
        "Function-generator transport URI.",
        "The URI selects native GPIB or a Prologix TCP/serial controller.",
        "ファンクションジェネレータ通信 URI",
        "native GPIB または Prologix TCP/serial の選択。",
        &["transport must be supported by the model and build features"],
    ),
    field(
        "data",
        "table",
        Required,
        None,
        &[],
        None,
        "Acquisition storage and analysis-input policy.",
        "Controls canonical waveform formats and optional screenshot capture.",
        "取得データ方針",
        "標準波形形式と任意スクリーンショット取得の設定。",
        &[],
    ),
    field(
        "data.output",
        "string enum",
        Required,
        None,
        &["csv", "raw", "both"],
        None,
        "Waveform format written by acquisition.",
        "Raw is preferred for very large captures; both also writes CSV.",
        "取得波形の保存形式",
        "大規模取得向け raw、CSV 併記向け both。",
        &[],
    ),
    field(
        "data.input",
        "string enum",
        Required,
        None,
        &["csv", "raw", "auto"],
        None,
        "Waveform source used by analysis.",
        "Auto selects available canonical data, preferring verified raw data.",
        "解析波形の入力形式",
        "利用可能な標準データを選ぶ auto。検証済み raw 優先。",
        &[],
    ),
    field(
        "data.screenshot",
        "boolean",
        Optional,
        Some("false"),
        &["true", "false"],
        None,
        "Oscilloscope screenshot capture.",
        "Capture requires a scope and transport that support display transfer.",
        "オシロスコープ画面取得",
        "display transfer 対応モデル・通信方式での任意取得。",
        &["DHO5108 capture requires TCP/IP or USB-TMC"],
    ),
    field(
        "sensors",
        "array of tables",
        Conditional,
        Some("[]"),
        &[],
        None,
        "Sensor-channel metadata and scaling.",
        "Each entry assigns one channel and exactly one scaling strategy.",
        "センサーチャンネル一覧",
        "各 channel と単一 scale 方針の対応。",
        &["channels must not overlap reference or lock-in signal channels"],
    ),
    field(
        "sensors[].channel",
        "integer",
        Required,
        None,
        &[],
        None,
        "Oscilloscope sensor channel.",
        "The current DHO5108 mapping accepts channels 1 through 8.",
        "センサーチャンネル番号",
        "DHO5108 向け 1 以上 8 以下の番号。",
        &["1 <= value <= 8", "must be unique across all channel roles"],
    ),
    field(
        "sensors[].scale",
        "inline table union",
        Required,
        None,
        &["{ factor = ... }", "{ max_abs = ..., polarity = ... }"],
        None,
        "Sensor conversion rule.",
        "Choose direct multiplication or maximum-absolute normalization.",
        "センサー変換規則",
        "直接係数または最大絶対値正規化の択一。",
        &["factor and max_abs forms are mutually exclusive"],
    ),
    field(
        "sensors[].scale.factor",
        "float",
        Conditional,
        None,
        &[],
        None,
        "Linear sensor conversion factor.",
        "Multiplies the integrated sensor values directly.",
        "線形センサー変換係数",
        "積分センサー値への直接乗算。",
        &["must be finite and non-zero"],
    ),
    field(
        "sensors[].scale.max_abs",
        "float",
        Conditional,
        None,
        &[],
        None,
        "Target maximum absolute sensor value.",
        "Normalizes the measured absolute maximum to this positive target.",
        "最大絶対値の正規化目標",
        "測定最大絶対値に対応する正の目標値。",
        &["must be finite and positive"],
    ),
    field(
        "sensors[].scale.polarity",
        "integer enum",
        Conditional,
        None,
        &["-1", "1"],
        None,
        "Polarity for maximum-absolute scaling.",
        "Required with max_abs scaling.",
        "最大絶対値正規化の極性",
        "max_abs 使用時の必須符号。",
        &["must equal -1 or 1"],
    ),
    field(
        "sensors[].label",
        "string",
        Required,
        None,
        &[],
        None,
        "Plot label for the sensor.",
        "Matplotlib mathtext may be supplied as a TOML literal string.",
        "センサープロットラベル",
        "TOML literal string で指定可能な Matplotlib mathtext。",
        &["must not be empty"],
    ),
    field(
        "sensors[].unit",
        "string",
        Required,
        None,
        &[],
        None,
        "Output unit for the scaled sensor.",
        "Used in tables, plots, and saved analysis headers.",
        "変換後センサーの出力単位",
        "表・プロット・解析保存ヘッダーでの単位。",
        &["must not be empty"],
    ),
    field(
        "pulse",
        "table",
        Required,
        None,
        &[],
        None,
        "Pulse background windows.",
        "Defines baseline regions before and after the pulse.",
        "パルス背景区間",
        "パルス前後のベースライン領域。",
        &["background windows must not overlap"],
    ),
    field(
        "pulse.background_before",
        "inline time window",
        Required,
        None,
        &[],
        Some("s"),
        "Background window before the pulse.",
        "An inline table with finite start and end values.",
        "パルス前背景区間",
        "有限な start と end の inline table。",
        &["start < end"],
    ),
    field(
        "pulse.background_after",
        "inline time window",
        Required,
        None,
        &[],
        Some("s"),
        "Background window after the pulse.",
        "An inline table with finite start and end values.",
        "パルス後背景区間",
        "有限な start と end の inline table。",
        &["start < end"],
    ),
    field(
        "reference",
        "table",
        Required,
        None,
        &[],
        None,
        "Optical reference analysis settings.",
        "Controls the reference channel, FFT region, and fit decimation.",
        "光学参照信号の解析設定",
        "reference channel、FFT 区間、fit 間引きの指定。",
        &[],
    ),
    field(
        "reference.channel",
        "integer",
        Required,
        None,
        &[],
        None,
        "Reference oscilloscope channel.",
        "The current DHO5108 mapping accepts channels 1 through 8.",
        "参照信号チャンネル",
        "DHO5108 向け 1 以上 8 以下の番号。",
        &["1 <= value <= 8", "must be unique across all channel roles"],
    ),
    field(
        "reference.fft_window",
        "inline time window",
        Required,
        None,
        &[],
        Some("s"),
        "Time range used by the reference FFT.",
        "Choose a stable reference segment with finite start and end values.",
        "参照 FFT 時間区間",
        "安定した参照信号区間を表す有限な start と end。",
        &["start < end"],
    ),
    field(
        "reference.stride_samples",
        "integer",
        Required,
        None,
        &[],
        Some("samples"),
        "Reference-fit decimation stride.",
        "Larger values reduce fitting cost at the expense of temporal detail.",
        "参照 fit の間引き幅",
        "計算量と時間詳細度の調整値。",
        &["must be positive"],
    ),
    field(
        "reference.window_samples",
        "integer",
        Required,
        None,
        &[],
        Some("samples"),
        "Local reference-fitting window size.",
        "Used around the FFT estimate by reference analysis.",
        "局所参照 fit の窓幅",
        "FFT 推定値周辺で使用する sample 数。",
        &["must be positive"],
    ),
    field(
        "lockin",
        "table",
        Required,
        None,
        &[],
        None,
        "Numerical lock-in settings.",
        "Defines signal channels, parallelism, output stride, and low-pass filtering.",
        "数値 lock-in 設定",
        "信号 channel、並列度、出力間引き、low-pass filter の指定。",
        &[],
    ),
    field(
        "lockin.signal_channels",
        "integer array",
        Conditional,
        None,
        &[],
        None,
        "Channels demodulated by lock-in analysis.",
        "At least one channel is required by lock-in and downstream analysis.",
        "lock-in 復調対象チャンネル",
        "lock-in と後段解析で必要な 1 件以上の番号。",
        &[
            "each value must be in 1..=8",
            "must be unique across all channel roles",
        ],
    ),
    field(
        "lockin.workers",
        "integer",
        Required,
        None,
        &[],
        None,
        "Parallel lock-in worker count.",
        "Values near the physical CPU count are a practical starting point.",
        "lock-in 並列 worker 数",
        "物理 CPU 数付近を初期値とする並列度。",
        &["must be positive"],
    ),
    field(
        "lockin.stride_samples",
        "integer",
        Required,
        None,
        &[],
        Some("samples"),
        "Lock-in output stride in input samples.",
        "Input sample rate divided by this value gives the output sample rate.",
        "lock-in 出力間引き幅",
        "入力 sample rate を除算する sample 数。",
        &["must be positive"],
    ),
    field(
        "lockin.filter",
        "tagged inline table",
        Required,
        None,
        &[],
        None,
        "Lock-in low-pass filter configuration.",
        "Fields accepted by the table depend on the selected kind.",
        "lock-in low-pass filter 設定",
        "kind ごとに異なる許可 field。",
        &["fields from other filter kinds are rejected"],
    ),
    field(
        "lockin.filter.kind",
        "string enum",
        Required,
        None,
        &[
            "boxcar_legacy",
            "fir_boxcar_enbw",
            "fir_zero_phase",
            "sync_iir_zero_phase",
        ],
        None,
        "Lock-in filter algorithm.",
        "sync_iir_zero_phase combines synchronous averaging and zero-phase IIR smoothing.",
        "lock-in filter アルゴリズム",
        "同期平均と zero-phase IIR 平滑化を組み合わせる sync_iir_zero_phase。",
        &[],
    ),
    field(
        "lockin.filter.half_window_cycles",
        "float",
        Required,
        None,
        &[],
        Some("reference cycles"),
        "Half-window scale in reference cycles.",
        "For sync_iir_zero_phase it defines half of the synchronous-average window.",
        "参照周期単位の半窓幅",
        "sync_iir_zero_phase の同期平均 full window の半分。",
        &["must be finite and positive"],
    ),
    field(
        "lockin.filter.cutoff_hz",
        "float",
        Optional,
        Some("absent"),
        &[],
        Some("Hz"),
        "Absolute low-pass cutoff.",
        "Accepted by cutoff-based FIR and IIR filters.",
        "絶対 low-pass cutoff",
        "cutoff 型 FIR/IIR filter で使用する周波数。",
        &[
            "must be finite and positive",
            "mutually exclusive with cutoff_ref_ratio",
        ],
    ),
    field(
        "lockin.filter.cutoff_ref_ratio",
        "float",
        Optional,
        Some("absent"),
        &[],
        Some("f_ref ratio"),
        "Low-pass cutoff relative to the fitted reference frequency.",
        "A value of 0.02 gives a cutoff at two percent of f_ref.",
        "参照周波数比の low-pass cutoff",
        "0.02 で f_ref の 2% となる比率。",
        &[
            "must be finite and positive",
            "mutually exclusive with cutoff_hz",
        ],
    ),
    field(
        "lockin.filter.stopband_atten_db",
        "float",
        Conditional,
        Some("60.0"),
        &[],
        Some("dB"),
        "FIR stopband attenuation target.",
        "Used only by fir_zero_phase filter design.",
        "FIR stopband 減衰目標",
        "fir_zero_phase 設計のみで使用する dB 値。",
        &["must be finite and positive"],
    ),
    field(
        "lockin.filter.sync_average_cycles",
        "float",
        Conditional,
        Some("1.0"),
        &[],
        Some("reference cycles"),
        "Synchronous-average full-window length.",
        "Used only by sync_iir_zero_phase; two times half_window_cycles matches a symmetric full window.",
        "同期平均の full window 長",
        "sync_iir_zero_phase 専用。対称 full window では half_window_cycles の 2 倍。",
        &["0 < value <= 100", "must be finite"],
    ),
    field(
        "lockin.filter.iir_order",
        "integer enum",
        Conditional,
        Some("2"),
        &["2", "4", "6", "8"],
        None,
        "IIR filter order.",
        "Used only by sync_iir_zero_phase.",
        "IIR filter 次数",
        "sync_iir_zero_phase 専用の偶数次数。",
        &[],
    ),
    field(
        "lockin.debug_output",
        "boolean",
        Optional,
        Some("false"),
        &["true", "false"],
        None,
        "Lock-in debug artifact output.",
        "Enable only for filter inspection because artifacts can be large.",
        "lock-in debug artifact 出力",
        "filter 調査時のみ有効化する大容量出力。",
        &[],
    ),
    field(
        "lockin.debug_label",
        "string",
        Optional,
        Some("absent"),
        &[],
        None,
        "Safe suffix for debug artifacts.",
        "The label is restricted to a short ASCII filename-safe subset.",
        "debug artifact の安全な suffix",
        "短い ASCII filename-safe 文字列。",
        &[
            "1-64 ASCII alphanumeric, '.', '_', or '-'",
            "must not be '.' or '..'",
        ],
    ),
    field(
        "lockin.debug_overwrite",
        "boolean",
        Optional,
        Some("false"),
        &["true", "false"],
        None,
        "Debug artifact overwrite policy.",
        "Allows replacement of an existing matching debug output.",
        "debug artifact 上書き方針",
        "同名 debug 出力の置換許可。",
        &[],
    ),
    field(
        "lockin.snr_background_window",
        "inline time window",
        Optional,
        Some("absent"),
        &[],
        Some("s"),
        "Optional background window for SNR diagnostics.",
        "An inline table with finite start and end values.",
        "SNR 診断用背景区間",
        "有限な start と end の任意 inline table。",
        &["start < end"],
    ),
    field(
        "lockin.snr_signal_window",
        "inline time window",
        Optional,
        Some("absent"),
        &[],
        Some("s"),
        "Optional signal window for SNR diagnostics.",
        "An inline table with finite start and end values.",
        "SNR 診断用信号区間",
        "有限な start と end の任意 inline table。",
        &["start < end"],
    ),
    field(
        "lockin.save_npy",
        "boolean",
        Optional,
        Some("false"),
        &["true", "false"],
        None,
        "NumPy output for lock-in results.",
        "Writes NPY artifacts in addition to canonical CSV results.",
        "lock-in 結果の NumPy 出力",
        "標準 CSV に追加する NPY artifact。",
        &[],
    ),
    field(
        "phase",
        "table",
        Required,
        None,
        &[],
        None,
        "Phase-rotation settings.",
        "Contains offsets for the first six harmonic components.",
        "位相回転設定",
        "第 1 から第 6 高調波の offset。",
        &[],
    ),
    field(
        "phase.offsets",
        "float or expression array",
        Required,
        None,
        &[],
        Some("rad"),
        "Six harmonic phase offsets.",
        "Numeric expressions such as pi/2 are accepted.",
        "6 高調波の位相 offset",
        "pi/2 などの数式指定に対応する rad 値。",
        &["must contain exactly 6 finite values"],
    ),
    field(
        "kerr",
        "table",
        Required,
        None,
        &[],
        None,
        "Kerr-angle conversion settings.",
        "Selects calibration sensor, calculation method, and final factor.",
        "Kerr 角変換設定",
        "校正 sensor、計算法、最終係数の指定。",
        &[],
    ),
    field(
        "kerr.sensor",
        "integer",
        Required,
        None,
        &[],
        None,
        "Sensor channel used for Kerr calibration.",
        "The channel must also exist in the sensors array.",
        "Kerr 校正用センサーチャンネル",
        "sensors 配列に存在する channel。",
        &["must reference sensors[].channel"],
    ),
    field(
        "kerr.method",
        "string enum",
        Required,
        None,
        &["standard", "harmonics"],
        None,
        "Kerr calculation method.",
        "Selects the standard or harmonic analysis implementation.",
        "Kerr 計算法",
        "standard または harmonics 実装の選択。",
        &[],
    ),
    field(
        "kerr.factor",
        "float",
        Required,
        None,
        &[],
        None,
        "Final Kerr conversion factor.",
        "Applied after the selected Kerr calculation.",
        "最終 Kerr 変換係数",
        "選択した Kerr 計算後の乗算値。",
        &["must be finite"],
    ),
    field(
        "plot",
        "table",
        Optional,
        Some("defaults"),
        &[],
        None,
        "Plot generation settings.",
        "Controls display/save behavior, decimation, and error policy.",
        "プロット生成設定",
        "表示・保存、間引き、失敗方針の指定。",
        &[],
    ),
    field(
        "plot.mode",
        "string enum",
        Optional,
        Some("save"),
        &["off", "save", "interactive", "both"],
        None,
        "Plot output mode.",
        "Batch use normally selects save; interactive opens Matplotlib windows.",
        "プロット出力 mode",
        "batch 向け save と Matplotlib window 向け interactive。",
        &[],
    ),
    field(
        "plot.max_points",
        "integer",
        Optional,
        Some("100000"),
        &[],
        Some("points per series"),
        "Maximum points passed to plotting.",
        "Lower values improve Matplotlib responsiveness on large captures.",
        "プロット入力の最大点数",
        "大規模取得時の Matplotlib 応答性調整値。",
        &["must be positive"],
    ),
    field(
        "plot.decimation",
        "string enum",
        Optional,
        Some("stride"),
        &["none", "stride", "min_max"],
        None,
        "Plot downsampling algorithm.",
        "min_max preserves narrow extrema better than stride decimation.",
        "プロット間引きアルゴリズム",
        "狭い極値の保持に適した min_max。",
        &[],
    ),
    field(
        "plot.on_error",
        "string enum",
        Optional,
        Some("warn"),
        &["warn", "fail"],
        None,
        "Plot failure policy.",
        "Warn preserves successful analysis; fail makes plotting errors fatal.",
        "プロット失敗方針",
        "解析成功を保持する warn と致命扱いの fail。",
        &[],
    ),
    field(
        "plot.output_dir",
        "string",
        Optional,
        Some("absent"),
        &[],
        None,
        "Deprecated plot directory compatibility field.",
        "Version 4 accepts but ignores this field; artifacts use the canonical run layout.",
        "非推奨のプロット directory 互換 field",
        "version 4 で受理後に無視される値。artifact は標準 run layout。",
        &["ignored with a warning"],
    ),
];

pub fn config_reference() -> ConfigReference {
    ConfigReference {
        format_version: DOCS_FORMAT_VERSION,
        pmoke_version: env!("CARGO_PKG_VERSION"),
        schema_version: LATEST_CONFIG_VERSION,
        fields: CONFIG_FIELD_DOCS,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;

    #[test]
    fn field_ids_are_unique_and_stable_paths() {
        let mut ids = BTreeSet::new();
        for field in CONFIG_FIELD_DOCS {
            assert_eq!(field.id, field.path);
            assert!(ids.insert(field.id), "duplicate config field: {}", field.id);
            assert!(!field.summary_en.is_empty());
            assert!(!field.summary_ja.is_empty());
        }
    }

    #[test]
    fn reference_uses_current_versions() {
        let reference = config_reference();
        assert_eq!(reference.pmoke_version, env!("CARGO_PKG_VERSION"));
        assert_eq!(reference.schema_version, LATEST_CONFIG_VERSION);
    }
}
