[package]
name = "instruments"
version = "0.2.3"
edition = "2024"

[features]
default = ["gpib"]
gpib = ["dep:gpib-rs"]
prologix-tcp = ["dep:prologix-rs", "prologix-rs/tcp"]
prologix-serial = ["dep:prologix-rs", "prologix-rs/serial"]

[dependencies]
gpib-rs = { path = "../gpib-rs", optional = true }
prologix-rs = { path = "../prologix-rs", optional = true, default-features = false }
anyhow = "1.0.104"

[[example]]
name = "dummy"
path = "./examples/dummy/dummy.rs"

[[example]]
name = "keithley2000"
path = "./examples/keithley/keithley2000.rs"
required-features = ["gpib"]

[[example]]
name = "keithley2010_prologix_tcp"
path = "./examples/keithley/keithley2010_prologix_tcp.rs"
required-features = ["prologix-tcp"]

[[example]]
name = "dho5108"
path = "./examples/rigol/dho5108.rs"

[[example]]
name = "wf1946b"
path = "./examples/nf/wf1946b.rs"
required-features = ["gpib"]
