use anyhow::Result;
use pmoke::config::{ConfigFieldDoc, ConfigReference, LATEST_CONFIG_VERSION, RequiredState};
use pmoke::docs::{ArgumentDoc, ArgumentKind, CliReference, CommandDoc};
use std::fmt::Write;

#[derive(Clone, Copy, Debug)]
pub enum Locale {
    English,
    Japanese,
}

impl Locale {
    pub fn code(self) -> &'static str {
        match self {
            Self::English => "en",
            Self::Japanese => "ja",
        }
    }
}

pub fn render_cli(reference: &CliReference, locale: Locale) -> Result<String> {
    let mut output = String::new();
    let (title, description, generated, commands_title, global_title) = match locale {
        Locale::English => (
            "CLI Reference",
            "Generated command and option reference for the complete pmoke feature set.",
            "Generated from typed clap metadata. Manual edits are overwritten.",
            "Command index",
            "Global options",
        ),
        Locale::Japanese => (
            "CLI リファレンス",
            "pmokeの全featureを対象とする、commandとoptionの自動生成リファレンス。",
            "型付きclap metadataから自動生成。手動編集は上書き対象。",
            "コマンド索引",
            "グローバル option",
        ),
    };
    write!(
        output,
        "---\ntitle: {title}\ndescription: {description}\n---\n\n{{/* generated by cargo xtask docs-export */}}\n\n> {generated}\n\n"
    )?;
    metadata(
        &mut output,
        reference.pmoke_version,
        LATEST_CONFIG_VERSION,
        locale,
    )?;
    writeln!(output, "## {commands_title}\n")?;
    writeln!(
        output,
        "| {} | {} | {} |",
        label(locale, "Command", "コマンド"),
        label(locale, "Description", "説明"),
        label(locale, "Feature", "必要なfeature")
    )?;
    writeln!(output, "| --- | --- | --- |")?;
    for command in &reference.command.subcommands {
        writeln!(
            output,
            "| [`{}`](#{}) | {} | {} |",
            command.path,
            anchor(&command.path),
            translated(&command.summary, locale)?,
            command.required_feature.unwrap_or("core")
        )?;
    }
    writeln!(output, "\n## {global_title}\n")?;
    argument_table(&mut output, &reference.command.arguments, locale)?;
    for command in &reference.command.subcommands {
        render_command(&mut output, command, 2, locale)?;
    }
    Ok(output)
}

pub fn render_config(reference: &ConfigReference, locale: Locale) -> String {
    let mut output = String::new();
    let (title, description, generated, schema_label) = match locale {
        Locale::English => (
            "Configuration Reference",
            "Generated field reference for pmoke config schema version 5.",
            "Generated from the typed config metadata registry. Manual edits are overwritten.",
            "JSON Schema",
        ),
        Locale::Japanese => (
            "設定リファレンス",
            "pmoke config schema version 5の自動生成fieldリファレンス。",
            "型付きconfig metadata registryから自動生成。手動編集は上書き対象。",
            "JSON Schema",
        ),
    };
    writeln!(
        output,
        "---\ntitle: {title}\ndescription: {description}\n---\n\n{{/* generated by cargo xtask docs-export */}}\n\n> {generated}\n"
    )
    .unwrap();
    metadata(
        &mut output,
        reference.pmoke_version,
        reference.schema_version,
        locale,
    )
    .unwrap();
    writeln!(
        output,
        "[{schema_label}](https://kerr-group.github.io/pmoke/config.schema.json) · [`pmoke config explain`](../../cli/reference#pmoke-config-explain)\n"
    )
    .unwrap();

    let mut current_group = "";
    for field in reference.fields {
        let group = field.path.split('.').next().unwrap_or(field.path);
        if group != current_group {
            current_group = group;
            writeln!(output, "## `{group}`\n").unwrap();
            config_table_header(&mut output, locale).unwrap();
        }
        config_row(&mut output, field, locale).unwrap();
    }
    output
}

fn render_command(
    output: &mut String,
    command: &CommandDoc,
    level: usize,
    locale: Locale,
) -> Result<()> {
    let hashes = "#".repeat(level);
    writeln!(output, "\n{hashes} `{}`\n", command.path)?;
    writeln!(output, "{}\n", translated(&command.summary, locale)?)?;
    if let Some(feature) = command.required_feature {
        writeln!(
            output,
            "> **{}:** `{feature}`\n",
            label(locale, "Required feature", "必要なfeature")
        )?;
    }
    writeln!(output, "```text\n{}\n```\n", usage(command))?;
    if !command.arguments.is_empty() {
        argument_table(output, &command.arguments, locale)?;
    }
    for subcommand in &command.subcommands {
        render_command(output, subcommand, level + 1, locale)?;
    }
    Ok(())
}

fn argument_table(output: &mut String, arguments: &[ArgumentDoc], locale: Locale) -> Result<()> {
    if arguments.is_empty() {
        writeln!(
            output,
            "{}\n",
            label(locale, "No options.", "option なし。")
        )?;
        return Ok(());
    }
    writeln!(
        output,
        "| {} | {} | {} | {} | {} |",
        label(locale, "Option", "option"),
        label(locale, "Required", "必須"),
        label(locale, "Default / values", "既定値 / 候補"),
        label(locale, "Description", "説明"),
        label(locale, "Conflicts", "競合")
    )?;
    writeln!(output, "| --- | :---: | --- | --- | --- |")?;
    for argument in arguments {
        let defaults = if argument.default_values.is_empty() {
            "-".to_string()
        } else {
            code_list(&argument.default_values)
        };
        let values = if argument.possible_values.is_empty() {
            defaults
        } else if argument.default_values.is_empty() {
            code_list(&argument.possible_values)
        } else {
            format!("{defaults}; {}", code_list(&argument.possible_values))
        };
        let conflicts = if argument.conflicts_with.is_empty() {
            "-".to_string()
        } else {
            code_list(&argument.conflicts_with)
        };
        writeln!(
            output,
            "| `{}` | {} | {} | {} | {} |",
            option_name(argument),
            if argument.required {
                label(locale, "yes", "必須")
            } else {
                "-"
            },
            values,
            escape_table(translated(&argument.help, locale)?),
            conflicts
        )?;
    }
    writeln!(output)?;
    Ok(())
}

fn usage(command: &CommandDoc) -> String {
    let mut parts = vec![command.path.clone()];
    for argument in &command.arguments {
        let value = option_name(argument);
        parts.push(if argument.required {
            value
        } else {
            format!("[{value}]")
        });
    }
    if !command.subcommands.is_empty() {
        parts.push("<COMMAND>".to_string());
    }
    parts.join(" ")
}

fn option_name(argument: &ArgumentDoc) -> String {
    let value = argument
        .value_names
        .first()
        .map(|name| format!(" <{name}>"))
        .unwrap_or_default();
    match argument.kind {
        ArgumentKind::Positional => argument
            .value_names
            .first()
            .map(|name| format!("<{name}>"))
            .unwrap_or_else(|| format!("<{}>", argument.id.to_uppercase())),
        ArgumentKind::Flag | ArgumentKind::Option => match (&argument.long, argument.short) {
            (Some(long), Some(short)) => format!("-{short}, --{long}{value}"),
            (Some(long), None) => format!("--{long}{value}"),
            (None, Some(short)) => format!("-{short}{value}"),
            (None, None) => argument.id.clone(),
        },
    }
}

fn metadata(output: &mut String, version: &str, schema: u32, _locale: Locale) -> std::fmt::Result {
    writeln!(
        output,
        "<ReferenceMetadata pmokeVersion=\"{version}\" schemaVersion={{{schema}}} />\n"
    )
}

fn config_table_header(output: &mut String, locale: Locale) -> std::fmt::Result {
    writeln!(
        output,
        "| {} | {} | {} | {} | {} |\n| --- | --- | :---: | --- | --- |",
        label(locale, "Path", "path"),
        label(locale, "Type", "型"),
        label(locale, "Required", "必須状態"),
        label(locale, "Default / values", "既定値 / 候補"),
        label(locale, "Description and constraints", "説明・制約")
    )
}

fn config_row(output: &mut String, field: &ConfigFieldDoc, locale: Locale) -> std::fmt::Result {
    let state = match (field.required, locale) {
        (RequiredState::Required, Locale::English) => "required",
        (RequiredState::Optional, Locale::English) => "optional",
        (RequiredState::Conditional, Locale::English) => "conditional",
        (RequiredState::Required, Locale::Japanese) => "必須",
        (RequiredState::Optional, Locale::Japanese) => "任意",
        (RequiredState::Conditional, Locale::Japanese) => "条件付き",
    };
    let default = field.default.map(|value| format!("`{value}`"));
    let values = (!field.valid_values.is_empty()).then(|| code_list(field.valid_values));
    let default_values = match (default, values) {
        (Some(default), Some(values)) => format!("{default}; {values}"),
        (Some(default), None) => default,
        (None, Some(values)) => values,
        (None, None) => "-".to_string(),
    };
    let (summary, details) = match locale {
        Locale::English => (field.summary_en, field.details_en),
        Locale::Japanese => (field.summary_ja, field.details_ja),
    };
    let constraints = if field.constraints.is_empty() {
        String::new()
    } else {
        format!(
            " **{}:** {}",
            label(locale, "Constraints", "制約"),
            field.constraints.join("; ")
        )
    };
    let units = field
        .units
        .map(|units| format!(" · `{units}`"))
        .unwrap_or_default();
    writeln!(
        output,
        "| `{}` | `{}`{units} | {state} | {default_values} | {} {}{} |",
        field.path,
        field.value_type,
        escape_table(summary),
        escape_table(details),
        escape_table(&constraints)
    )
}

fn translated(text: &str, locale: Locale) -> Result<&str> {
    match locale {
        Locale::English => Ok(text),
        Locale::Japanese => japanese(text)
            .ok_or_else(|| anyhow::anyhow!("missing Japanese CLI translation: {text}")),
    }
}

fn japanese(text: &str) -> Option<&'static str> {
    Some(match text {
        "A CLI tool to conduct pulsed MOKE experiments and analyze the data." => {
            "パルスMOKEの実験とデータ解析を行うCLI。"
        }
        "Display the contents of the configuration file" => "設定ファイルの内容表示",
        "Open a live terminal dashboard for configuration and analysis artifacts" => {
            "設定・解析artifactのライブ端末ダッシュボード"
        }
        "Inspect and migrate configuration files" => "設定ファイルの確認・移行",
        "Inspect and verify stored RAW waveform data" => "保存済みRAW波形の確認・検証",
        "Inspect supported instruments and hardware capabilities" => {
            "対応装置とhardware capabilityの確認"
        }
        "Benchmark instrument transport request latency" => {
            "装置transportのリクエスト遅延benchmark"
        }
        "Export stored data to interchange formats" => "保存データの交換形式export",
        "Diagnose config, storage, Python, and connected instruments" => {
            "設定、ストレージ、Python、接続装置の診断"
        }
        "Set single mode to the oscilloscope" => "オシロスコープのsingle mode設定",
        "Send trigger signal from the function generator" => {
            "ファンクションジェネレータからのtrigger送信"
        }
        "Set single mode and send trigger signal" => "single mode設定とtrigger送信",
        "Fetch data from the oscilloscope and save to a file" => "オシロスコープデータの取得・保存",
        "Capture an oscilloscope screenshot directly to the PC" => "オシロスコープ画面のPC直接取得",
        "Perform auto measurement (set single mode, trigger, fetch)" => {
            "single mode・trigger・fetchの自動測定"
        }
        "Analyze the reference signal" => "参照信号解析",
        "Analyze the sensor signal" => "センサー信号解析",
        "Run numerical lock-in analysis" => "数値lock-in解析",
        "Rotate the reference phase for lock-in analysis" => "lock-in解析の参照位相回転",
        "Calculate the Kerr angle" => "Kerr角計算",
        "Run all analysis steps: reference, sensor, lock-in, phase, Kerr" => {
            "reference・sensor・lock-in・phase・Kerrの全解析"
        }
        "Automated analysis after manually triggering the pulse (fetch, lock-in, phase, Kerr)" => {
            "手動pulse trigger後のfetch・lock-in・phase・Kerr自動解析"
        }
        "Run the full automatic measurement and analysis" => "完全自動測定・解析",
        "Generate shell completion script" => "shell completion scriptの生成",
        "Create a starter config file" => "初期設定ファイルの生成",
        "Validate the config file without running an analysis command" => {
            "解析を伴わない設定ファイル検証"
        }
        "Explain config sections and fields" => "設定section・fieldの説明",
        "Migrate the config to the latest executable schema" => "設定の最新実行可能schemaへの移行",
        "Verify RAW metadata, file sizes, and available checksums" => {
            "RAW metadata・file size・checksumの検証"
        }
        "List supported instrument models" => "対応装置モデル一覧",
        "Explain a supported instrument model" => "対応装置モデルの説明",
        "Send one SCPI text query to a connection URI" => "接続URIへの単一SCPI text query",
        "Benchmark one SCPI query and save a compact reproducibility report" => {
            "単一SCPI queryのbenchmarkと再現性report保存"
        }
        "Measure text request/response latency for a connection URI" => {
            "接続URIのtext request/response latency計測"
        }
        "Convert a verified RAW waveform directory to CSV" => "検証済みRAW波形directoryのCSV変換",
        "Convert analysis result CSV files to NumPy tables" => "解析結果CSVのNumPy table変換",
        "Path to the configuration file (default: ./config.toml)" => {
            "設定ファイルpath。既定値./config.toml。"
        }
        "Store and read run artifacts under this directory" => {
            "run artifactを保存・読み込むdirectory"
        }
        "Overwrite existing run artifacts without error" => "既存run artifactの上書き許可",
        "Print help" | "Print help (see a summary with '-h')" => "help表示",
        "Print version" => "version表示",
        "Write the template to FILE instead of --config; use '-' for standard output" => {
            "--configの代わりにFILEへtemplate出力。標準出力は'-'。"
        }
        "Overwrite an existing output file" => "既存出力ファイルの上書き許可",
        "Field or section path to explain, for example lockin.filter" => {
            "説明対象fieldまたはsection path。例: lockin.filter。"
        }
        "Write the migrated TOML to FILE; use '-' for standard output" => {
            "移行済みTOMLのFILE出力。標準出力は'-'。"
        }
        "Atomically replace the source config after creating a versioned backup" => {
            "version付きbackup作成後の設定原本のatomic置換"
        }
        "Only report whether a migration is required" => "移行要否のみの報告",
        "Accept migration steps that can change legacy behavior" => {
            "legacy動作を変更し得る移行stepの許可"
        }
        "Require a specific target version instead of the latest executable version" => {
            "最新実行可能版に代わる移行先versionの固定"
        }
        "RAW acquisition directory (defaults to acquisition/ with legacy fallback)" => {
            "RAW取得directory。既定値acquisition/、legacy fallbackあり。"
        }
        "Emit machine-readable JSON" => "machine-readable JSON出力",
        "Instrument model name, for example Keithley2010" => "装置モデル名。例: Keithley2010。",
        "Connection URI, for example prologix-tcp://host:1234?addr=17" => {
            "接続URI。例: prologix-tcp://host:1234?addr=17。"
        }
        "Timeout used when the URI does not include a transport-specific timeout" => {
            "URIにtransport固有のtimeoutがない場合に使用するtimeout"
        }
        "SCPI query command, for example *IDN?" => "SCPI query command。例: *IDN?。",
        "Connection URI accepted by `pmoke instruments query`" => {
            "`pmoke instruments query`で使用する接続URI"
        }
        "SCPI query command to benchmark" => "benchmark対象のSCPI query command",
        "Measured query count" => "計測するquery回数",
        "Unmeasured query count before measurement" => "計測前に実行する非記録query回数",
        "Timeout used when the URI has no transport-specific timeout" => {
            "URIにtransport固有のtimeoutがない場合に使用するtimeout"
        }
        "Save TOML to FILE instead of the run benchmark directory" => {
            "run benchmark directoryに代わるFILEへのTOML保存"
        }
        "Emit the compact report as JSON after saving TOML" => {
            "TOML保存後のcompact report JSON出力"
        }
        "Text protocol used to validate each request" => "各requestを検証するtext protocol",
        "Request to benchmark; repeat for multiple requests" => {
            "benchmark対象request。複数指定時の反復option。"
        }
        "Measured request count per request" => "requestごとの計測回数",
        "Unmeasured request count before each measurement" => "各計測前に実行する非記録request回数",
        "Save the complete JSON report to a file" => "完全JSON reportのファイル保存",
        "Emit the complete report as JSON" => "完全reportのJSON出力",
        "Emit a machine-readable JSON report" => "machine-readable JSON report出力",
        "Allow active checks such as stopping the oscilloscope" => {
            "オシロスコープ停止などのactive check許可"
        }
        "Override output format from config [fetch].output" => {
            "config [fetch].outputに対する出力形式override"
        }
        "CSV destination (defaults to acquisition/waveforms/waveform.csv)" => {
            "CSV出力先。既定値acquisition/waveforms/waveform.csv。"
        }
        "Destination directory (defaults to NPY files beside canonical analysis CSVs)" => {
            "出力directory。既定値は標準解析CSVと同じ場所のNPY。"
        }
        "Shell to generate for: bash, zsh, fish, powershell, elvish" => {
            "生成対象shell: bash、zsh、fish、powershell、elvish。"
        }
        _ => return None,
    })
}

fn label<'a>(locale: Locale, english: &'a str, japanese: &'a str) -> &'a str {
    match locale {
        Locale::English => english,
        Locale::Japanese => japanese,
    }
}

fn code_list(values: &[impl AsRef<str>]) -> String {
    values
        .iter()
        .map(|value| format!("`{}`", value.as_ref()))
        .collect::<Vec<_>>()
        .join(", ")
}

fn escape_table(value: &str) -> String {
    value
        .replace('|', "\\|")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('\n', " ")
}

fn anchor(path: &str) -> String {
    path.to_ascii_lowercase().replace(' ', "-")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_cli_string_has_a_japanese_translation() {
        let reference = pmoke::docs::cli_reference();
        render_cli(&reference, Locale::Japanese).unwrap();
    }

    #[test]
    fn generated_markdown_is_deterministic() {
        let reference = pmoke::docs::cli_reference();
        assert_eq!(
            render_cli(&reference, Locale::English).unwrap(),
            render_cli(&reference, Locale::English).unwrap()
        );
        let config = pmoke::config::config_reference();
        assert_eq!(
            render_config(&config, Locale::Japanese),
            render_config(&config, Locale::Japanese)
        );
    }
}
